language: ruby

rvm:
  - 2.3.1

install: bundle install

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --http-status-ignore "999" ./_site # Ignoring HTTP 999 because LinkedIn is silly

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# use container infrastructure on travis
sudo: false
