sudo: false 
dist: trusty
language: python
python:
  - "2.7"
before_install:
  - pip install virtualenv
  - sudo rm -f /etc/boto.cfg
install:
  - make
script:
  - make site
deploy:
  - provider: s3
    access_key_id: $PROD_AWS_ACCESS_KEY_ID
    secret_access_key: $PROD_AWS_SECRET_ACCESS_KEY
    bucket: "www.becker.am"
    skip_cleanup: true
    region: "us-east-1"
    local_dir: .build
    on:
      branch: master
  - provider: s3
    access_key_id: $DEV_AWS_ACCESS_KEY_ID
    secret_access_key: $DEV_AWS_SECRET_ACCESS_KEY
    bucket: "dev.becker.am"
    skip_cleanup: true
    region: "us-east-1"
    local_dir: .build
    on:
      all_branches: true
