# Site settings
name: Becker.am
my_name: Chris Becker
title: Chris Becker
email: chris@becker.am
description: "Infrastructure Engineer at Warby Parker and a lover of all things photography and bike related. NYC."
baseurl: ""
prod_url: "http://www.becker.am"
blog_image_url: "/images/blog"
me_image: "/images/chrisbecker.jpg"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
source: src
